[package]
name = "ehviewer_rust"
version = "0.0.0"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "*"
tl = "*"
log = "*"
android_logger = "*"
apply = "*"
regex = "*"
once_cell = "*"
quick-xml = "*"
