[package]
name = "ehviewer_rust"
version = "0.0.0"

[lib]
crate_type = ["cdylib"]

[dependencies]
tl = "*"
log = "*"
android_logger = "*"
apply = "*"
regex = "*"
once_cell = "*"
quick-xml = "*"
jnix = "*"
jnix-macros = "*"

[profile.release]
strip = true
opt-level = "z"
lto = true
